node {
   def mvnHome
   stage('Checkout') { // for display purposes
   
      // Get some code from a GitHub repository
      git (
       url: 'git@github.com:ankcha/projects.git',
       credentialsId: "${CREDENTIAL_ID}",
       branch: 'master'
      )
   }
   
   stage('Configure') {
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'M3'       
   }
   
   stage('Build') {
       
      // Run the maven build
      if (isUnix()) {
          dir('sample-project'){
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean install"
          }
      }  
      else {
              error("Build failed because this pipeline is being executed on Windows")
          }
   }
   
   stage('Run') {
       dir('sample-project'){
            if (isUnix()) {
                sh "java -cp target/dependency-graph-1.0-SNAPSHOT.jar com.graph.dependencies.App"
            } 
            else {
                error("Build failed because this pipeline is being executed on Windows")
            }
       }
   }
   
   stage('Results') {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
}
